version: 2

gomod:
  proxy: true

before:
  hooks:
    - go mod download

builds:
- id: forklift
  main: ./cmd/forklift
  binary: forklift
  mod_timestamp: "{{ .CommitTimestamp }}"
  flags:
    - -trimpath
  ldflags:
    - -w
    - -X main.buildSummary={{ .Summary }}
    - -X main.buildVersion={{ .Version }}
    - -X main.buildCommitFull={{ .FullCommit }}
    - -X main.buildCommitShort={{ .ShortCommit }}
    - -X main.buildCommitDate={{ .CommitDate }}
    - -X main.buildCommitTimestamp={{ .CommitTimestamp }}
    - -X main.buildReleaseURL={{ .ReleaseURL }}
    - -X main.buildRepo={{ .GitURL }}
    - -X main.buildSystem=goreleaser
  env:
    - CGO_ENABLED=0
  targets:
    - linux_amd64_v1
    - linux_arm64
    - linux_arm_7
    - darwin_amd64_v1
    - darwin_arm64
    - windows_amd64_v1
  overrides:
    - goos: darwin
      goarch: amd64
      goamd64: v1
      flags:
        - -trimpath
        - -buildmode=pie
      env:
        # CGo is needed for github.com/fsnotify/fsevents, which is needed by (probably) the Docker
        # Compose CLI
        - CGO_ENABLED=1
        # These toolchains are the ones provided by the goreleaser-cross Docker image:
        - CC=o64-clang
        - CXX=o64-clang++
    - goos: darwin
      goarch: arm64
      flags:
        - -trimpath
        - -buildmode=pie
      env:
        # CGo is needed for github.com/fsnotify/fsevents, which is needed by (probably) the Docker
        # Compose CLI
        - CGO_ENABLED=1
        # These toolchains are the ones provided by the goreleaser-cross Docker image:
        - CC=oa64-clang
        - CXX=oa64-clang++

archives:
  - id: forklift
    builds: ["forklift"]
    name_template: "forklift_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      formats:
        - zip

changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 10
    - title: Builds
      regexp: '^.*?build(\([[:word:]]+\))??!?:.+$'
      order: 20
    - title: etc
      order: 30
  filters:
    exclude:
      - '^.*?chore(\([[:word:]]+\))??!?:.+$'
      - '^.*?docs(\([[:word:]]+\))??!?:.+$'
      - '^.*?test(\([[:word:]]+\))??!?:.+$'
      - '^.*?ci(\([[:word:]]+\))??!?:.+$'

release:
  prerelease: auto
  footer: |
    **Full hand-crafted changelog**: [`CHANGELOG.md`]({{ .GitURL }}/blob/main/CHANGELOG.md)

    {{ if and .Tag .PreviousTag }}
      **Commit history**: [{{ .PreviousTag }}...{{ .Tag }}]({{ .GitURL }}/compare/{{ .Tag }}...{{ .PreviousTag }})
    {{ else if .PreviousTag }}
      **Commit history**: [{{ .PreviousTag }}...{{ .ShortCommit }}]({{ .GitURL }}/compare/{{ .Commit }}...{{ .PreviousTag }})
    {{ end }}

dockers:
  # forklift
  - id: forklift-amd64
    ids:
      - forklift
    dockerfile: "Dockerfile"
    use: buildx
    image_templates:
    - "ghcr.io/planktoscope/forklift:latest-amd64"
    - "ghcr.io/planktoscope/forklift:{{ .Major }}-amd64"
    - "ghcr.io/planktoscope/forklift:{{ .Major }}.{{ .Minor }}-amd64"
    - "ghcr.io/planktoscope/forklift:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
    build_flag_templates:
    - "--pull"
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.licenses=(Apache-2.0 OR BlueOak-1.0.0)"
  - id: forklift-arm64v8
    ids:
      - forklift
    dockerfile: "Dockerfile"
    use: buildx
    goarch: arm64
    image_templates:
    - "ghcr.io/planktoscope/forklift:latest-arm64v8"
    - "ghcr.io/planktoscope/forklift:{{ .Major }}-arm64v8"
    - "ghcr.io/planktoscope/forklift:{{ .Major }}.{{ .Minor }}-arm64v8"
    - "ghcr.io/planktoscope/forklift:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8"
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64/v8"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.licenses=(Apache-2.0 OR BlueOak-1.0.0)"
  - id: forklift-armv7
    ids:
      - forklift
    dockerfile: "Dockerfile"
    use: buildx
    goarch: arm
    goarm: 7
    image_templates:
    - "ghcr.io/planktoscope/forklift:latest-armv7"
    - "ghcr.io/planktoscope/forklift:{{ .Major }}-armv7"
    - "ghcr.io/planktoscope/forklift:{{ .Major }}.{{ .Minor }}-armv7"
    - "ghcr.io/planktoscope/forklift:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-armv7"
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm/v7"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.licenses=(Apache-2.0 OR BlueOak-1.0.0)"

docker_manifests:
  # forklift
  - name_template: "ghcr.io/planktoscope/forklift:latest"
    image_templates:
      - "ghcr.io/planktoscope/forklift:latest-amd64"
      - "ghcr.io/planktoscope/forklift:latest-arm64v8"
      - "ghcr.io/planktoscope/forklift:latest-armv7"
  - name_template: "ghcr.io/planktoscope/forklift:{{ .Major }}"
    image_templates:
      - "ghcr.io/planktoscope/forklift:{{ .Major }}-amd64"
      - "ghcr.io/planktoscope/forklift:{{ .Major }}-arm64v8"
      - "ghcr.io/planktoscope/forklift:{{ .Major }}-armv7"
  - name_template: "ghcr.io/planktoscope/forklift:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/planktoscope/forklift:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/planktoscope/forklift:{{ .Major }}.{{ .Minor }}-arm64v8"
      - "ghcr.io/planktoscope/forklift:{{ .Major }}.{{ .Minor }}-armv7"
  - name_template: "ghcr.io/planktoscope/forklift:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "ghcr.io/planktoscope/forklift:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "ghcr.io/planktoscope/forklift:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8"
      - "ghcr.io/planktoscope/forklift:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-armv7"
