before:
  hooks:
    - go mod download

builds:
- id: forklift
  main: ./cmd/forklift
  binary: forklift
  env:
    - CGO_ENABLED=0
  targets:
    - linux_amd64_v1
    - linux_arm64
    - linux_arm_7
    - darwin_amd64_v1
    - darwin_arm64
    - windows_amd64_v1

archives:
  - id: forklift
    builds: ["forklift"]
    name_template: "forklift_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip

release:
  github:
  prerelease: auto

dockers:
  # forklift
  - id: forklift-amd64
    ids:
      - forklift
    dockerfile: "Dockerfile.forklift"
    use: buildx
    image_templates:
    - "ghcr.io/PlanktoScope/forklift:latest-amd64"
    - "ghcr.io/PlanktoScope/forklift:{{ .Major }}-amd64"
    - "ghcr.io/PlanktoScope/forklift:{{ .Major }}.{{ .Minor }}-amd64"
    - "ghcr.io/PlanktoScope/forklift:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
    build_flag_templates:
    - "--pull"
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.licenses=(Apache-2.0 OR BlueOak-1.0.0)"
  - id: forklift-arm64v8
    ids:
      - forklift
    dockerfile: "Dockerfile.forklift"
    use: buildx
    goarch: arm64
    image_templates:
    - "ghcr.io/PlanktoScope/forklift:latest-arm64v8"
    - "ghcr.io/PlanktoScope/forklift:{{ .Major }}-arm64v8"
    - "ghcr.io/PlanktoScope/forklift:{{ .Major }}.{{ .Minor }}-arm64v8"
    - "ghcr.io/PlanktoScope/forklift:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8"
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64/v8"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.licenses=(Apache-2.0 OR BlueOak-1.0.0)"
  - id: forklift-armv7
    ids:
      - forklift
    dockerfile: "Dockerfile.forklift"
    use: buildx
    goarch: arm
    goarm: 7
    image_templates:
    - "ghcr.io/PlanktoScope/forklift:latest-armv7"
    - "ghcr.io/PlanktoScope/forklift:{{ .Major }}-armv7"
    - "ghcr.io/PlanktoScope/forklift:{{ .Major }}.{{ .Minor }}-armv7"
    - "ghcr.io/PlanktoScope/forklift:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-armv7"
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm/v7"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.licenses=(Apache-2.0 OR BlueOak-1.0.0)"

docker_manifests:
  # forklift
  - name_template: "ghcr.io/PlanktoScope/forklift:latest"
    image_templates:
      - "ghcr.io/PlanktoScope/forklift:latest-amd64"
      - "ghcr.io/PlanktoScope/forklift:latest-arm64v8"
      - "ghcr.io/PlanktoScope/forklift:latest-armv7"
  - name_template: "ghcr.io/PlanktoScope/forklift:{{ .Major }}"
    image_templates:
      - "ghcr.io/PlanktoScope/forklift:{{ .Major }}-amd64"
      - "ghcr.io/PlanktoScope/forklift:{{ .Major }}-arm64v8"
      - "ghcr.io/PlanktoScope/forklift:{{ .Major }}-armv7"
  - name_template: "ghcr.io/PlanktoScope/forklift:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/PlanktoScope/forklift:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/PlanktoScope/forklift:{{ .Major }}.{{ .Minor }}-arm64v8"
      - "ghcr.io/PlanktoScope/forklift:{{ .Major }}.{{ .Minor }}-armv7"
  - name_template: "ghcr.io/PlanktoScope/forklift:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "ghcr.io/PlanktoScope/forklift:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "ghcr.io/PlanktoScope/forklift:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8"
      - "ghcr.io/PlanktoScope/forklift:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-armv7"
