name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  merge_group:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: make ci

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}
          path: coverage.*

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.4.1
        with:
          file: ./coverage.out
          flags: ${{ runner.os }}

  release-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.mod

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Prepare Go package cache for cross-compilation
        run: |
          chmod +w -R ~/go/pkg

      - name: Set up Zig for CGo cross-compilation
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0

      - name: Set up the zig build cache
        id: zig-build-cache
        run: |
          destination="$HOME/zig-build"
          mkdir -p "$destination"
          echo "destination=$destination" >> $GITHUB_OUTPUT

      - name: Set up caching for the Zig build cache
        uses: Hanaasagi/zig-action-cache@v1.1.5
        env:
          ZIG_GLOBAL_CACHE_DIR: ${{ steps.zig-build-cache.outputs.destination }}
          ZIG_LOCAL_CACHE_DIR: ${{ steps.zig-build-cache.outputs.destination }}

      - name: Download macOS SDK for cross-compilation
        uses: ethanjli/cached-download-action@v0.1.2
        with:
          url: https://github.com/joseluisq/macosx-sdks/releases/download/13.3/MacOSX13.3.sdk.tar.xz
          destination: /tmp/MacOSX13.3.sdk.tar.xz

      - name: Prepare macOS SDK for cross-compilation
        run: |
          tar -xJf /tmp/MacOSX13.3.sdk.tar.xz -C /tmp

      - name: Release test
        env:
          MACOS_SDK: /tmp/MacOSX13.3.sdk
          ZIG_GLOBAL_CACHE_DIR: ${{ steps.zig-build-cache.outputs.destination }}
          ZIG_LOCAL_CACHE_DIR: ${{ steps.zig-build-cache.outputs.destination }}
        run: make build

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist
