name: build

on:
  push: 
    branches: 
      - main
  pull_request:
    branches: [ main ]
  merge_group:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod

      - name: Build
        run: make ci

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.*

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          file: ./coverage.out
          flags: ${{ runner.os }}

  release-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Release test
        run: make build
