name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod

      - name: Setup Docker image cache
        uses: ScribeMD/docker-cache@0.3.4
        with:
          # The Makefile specifies the version of the goreleaser-cross docker image to use, so we
          # use the Makefile for the hash key.
          key: docker-${{ runner.os }}-${{ hashFiles('Makefile') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
