name: release-draft

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Set up Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.mod

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Draft Tag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if ! git tag -d edge/draft; then
            echo "No draft tag to delete!"
          fi
          git tag edge/draft

      - name: Update Draft Tag
        # Note: we need a newer commit than the latest tagged release in order to use
        # push_only_tags, which we need to prevent the action from trying to push to protected
        # branches:
        uses: ad-m/github-push-action@77c5b412c50b723d2a4fbc6d71fb5723bcd439aa
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push_only_tags: true
          tags: true
          force: true

      - name: Release Draft
        run: make release-draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
