name: release-draft

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Set up Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.mod

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Draft Tag
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: edge/draft

      - name: Release Draft
        run: make release-draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
